language: cpp

compiler:
  - clang
  - gcc

addons:
  apt: &apt-global
    sources: &apt-common-sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages: &apt-common-packages
      - clang-3.8
      - g++-5
      - gcc-5
      - automake
      - autoconf
      - libtool

before_install:

install:

before_script:
  # g++
  - if [ "${CXX}" = 'g++' ]; then export CXX=g++-5; fi
  # clang
  - if [ "${CXX}" = 'clang++' ]; then export CXX=clang++-3.8; fi
  # mingw
  - if [ "${MINGW}" = '1' ]; then export CXX=i686-w64-mingw32-g++; fi
  - ./bootstrap

script:
  - if [ "${CXX}" = 'g++' ]; then ./configure && make; fi
  # clang
  - if [ "${CXX}" = 'clang++' ]; then ./configure && make; fi
  # mingw
  - if [ "${MINGW}" = '1' ]; then ./cross-i686-w64-mingw32.sh; fi

matrix:
  include:
    - compiler: clang++
      env:
    - compiler: g++
      env:
    - compiler: gcc
      env: MINGW=1
      before_install:
        - sudo apt-get -qq update
      install:
        - sudo apt-get -qq -y install wine
      addons:
        apt:
          sources: *apt-common-sources
          packages:
            - *apt-common-packages
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
