language: cpp
compiler:
  - g++
  - clang++
before_script:
  - ./bootstrap && ./configure && make
script:
branches:
  only:
    - master
notifications:
  recipients:
    - newserver002@gmail.com
  email:
    on_success: change
    on_failure: always