language: cpp
compiler:
  - g++
  - clang++
install:
   - sudo apt-get install -qq gnulib
before_script:
  - autoreconf -i -I/usr/share/gnulib/m4 -I `pwd`/m4 && ./configure && make
script:
branches:
  only:
    - master
notifications:
  recipients:
    - newserver002@gmail.com
  email:
    on_success: change
    on_failure: always